export const NOTHING = "NOTHING";
export const SET_FIREBASE_AUTH_USER = "SET_FIREBASE_AUTH_USER";
export const REMOVE_FIREBASE_AUTH = "REMOVE_FIREBASE_AUTH";
export const REMOVE_DONKOMI_USER_AUTH = "REMOVE_DONKOMI_USER_AUTH";
export const SET_DONKOMI_USER = "SET_DONKOMI_USER";
export const SHOW_FLOATING_MODAL = "SHOW_FLOATING_MODAL";