import { combineReducers } from "redux";
import {
  doNothingReducer,
  firebaseAuthUserReducer,
  setDonkomiUserReducer,
  setUserShopItemsReducer,
  setUserShopsReducer,
  showFloatingModalReducer,
  setAvailableRolesReducer,
  setVendorsReducer,
  setRoutinesReducer,
  setStockReducer,
  setCampaignReducer,
  setNewsParamsReducer,
  loadNewsReducer,
  marketNewsReducer,
  marketNewsParamsReducer,
  merchantCartReducer,
  cartReducer,
  setOrderHistoryReducer,
  campaignCartReducer,
  setSellerOrdersReducer,
  setMerchantOrdersReducer,
  setApplicationTokenReducer,
} from "./reducers";

export default combineReducers({
  nothing: doNothingReducer,
  fireAuth: firebaseAuthUserReducer,
  user: setDonkomiUserReducer,
  modal: showFloatingModalReducer,
  shops: setUserShopsReducer,
  products: setUserShopItemsReducer,
  roles: setAvailableRolesReducer,
  routines: setRoutinesReducer,
  vendors: setVendorsReducer,
  stock: setStockReducer,
  campaigns: setCampaignReducer,
  news: loadNewsReducer,
  newsParams: setNewsParamsReducer,
  market: marketNewsReducer,
  marketParams: marketNewsParamsReducer,
  cart: cartReducer,
  merchantCar: merchantCartReducer,
  orderHistory: setOrderHistoryReducer,
  campaignCart: campaignCartReducer, 
  sellerOrders: setSellerOrdersReducer, 
  merchantOrders: setMerchantOrdersReducer,
  deviceToken: setApplicationTokenReducer, //fcm device token
});
